server:
  port: 8801
spring:
  application:
    name: UserServer
  profiles:
    active: dev
  config:
    import: "optional:nacos:${spring.application.name}-${spring.profiles.active}.properties?refreshEnabled=true"
  nacos:
    username: nacos
    password: nacos
    config:
      server-addr: 127.0.0.1:8848
    discovery:
      server-addr: 127.0.0.1:8848
  cloud:
    sentinel:
      transport:
        dashboard: "127.0.0.1:8858"
        heartbeatIntervalMs: 15000
        port: 8720
feign:
  sentinel:
    enabled: true